---
# tasks file for aptly
- name: create aptly user
  user: name=aptly home={{ aptly_home }}

- name: create public directory
  file: path={{ aptly_home }}/public state=directory mode=0755 owner=aptly group=aptly

- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: import aptly repo key
  become: yes
  become_user: root
  apt_key: id=E083A3782A194991 keyserver=keys.gnupg.net state=present

- name: add aptly debian repository
  become: yes
  become_user: root
  apt_repository: repo='deb http://repo.aptly.info/ squeeze main' state=present update_cache=yes

- name: install required packages
  become: yes
  become_user: root
  apt: name={{ item }} state=present
  with_items:
    - gnupg2
    - rng-tools
    - aptly

- name: check for aptly pub key
  stat: path={{ aptly_home }}/key.pub
  register: gpg_pub_key

- name: check for aptly pub key
  stat: path={{ aptly_home }}/key.sec
  register: gpg_sec_key

- include: tasks/generate_key.yml
  when: (not gpg_pub_key.stat.exists) or (not gpg_sec_key.stat.exists)

- name: set aptly repo directory permissions
  file: path={{ aptly_home }} mode=0755

- name: create aptly configuration file
  template: src=etc/aptly.conf.j2 dest=/etc/aptly.conf
  notify: 
    - restart aptly

- name: aptly upstart service
  template: src=etc/init/aptly.conf.j2 dest=/etc/init/aptly.conf
  notify:
    - restart aptly

