---
- name: install aptly
  hosts: aptly

  vars_files:
    # secrets live here, you'll have to create this
    - vars/aptly.yml


  roles:
    - role: ansible-role-aptly
      aptly_key_email: bliles@digitalocean.com
      aptly_company_name: DigitalOcean
      aptly_user: aptly
    - role: ansible-role-nginx
      nginx_sites:
        default:
          - listen 80
          - server_name _
          - root "{{ aptly_home }}/public"
          - location / { autoindex on; }
          - |
            location /api {
              proxy_pass http://127.0.0.1:8080/api;
              auth_basic "Restricted";
              auth_basic_user_file auth_basic/api;
            }
      nginx_configs:
        http:
          - client_max_body_size 100m

      nginx_auth_basic_files:
        api:
          - "{{ apiauth }}"

