---
- name: install aptly
  hosts: apt-servers

  roles:
    - role: pre
    - role: ansible-role-aptly
      become: yes
      become_user: aptly
      aptly_key_email: bliles@digitalocean.com
      aptly_company_name: DigitalOcean
      aptly_user: aptly
    - role: ansible-role-nginx
      nginx_sites:
        default:
          - listen 80
          - server_name _
          - root "/usr/share/nginx/aptly/public"
          - location /api { proxy_pass http://127.0.0.1:8080/api; }
      nginx_configs:
        http:
          - client_max_body_size 100m
    - role: post

